version: "3.8"

networks:
  web-network:

volumes:
  postgres.data:
    external: true

services:
  app :
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db

  db:
    build:
      context: db
      dockerfile: Dockerfile
    tty: true
    volumes:
      - postgres.data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - web-network