version: "3.8"

networks:
  web-network:

volumes:
  clickhouse.data:
    external: true

services:
  app :
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web-network

  db:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse.data:/var/lib/clickhouse
    env_file:
      - .env
    environment:
      - CLICKHOUSE_USER=${APP_USER}
      - CLICKHOUSE_PASSWORD=${APP_PASSWORD}
    networks:
      - web-network